engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 50
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"

ratings:
  paths:
    - "**.py"
