engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  pep8:
    enabled: true
  radon:
    enabled: true

ratings:
  paths:
    - "**.py"
