matrix:
  include:
    - os: linux
      language: python
      sudo: false
      python: 3.5
    - os: osx
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zoidbergwill/python/python35; fi

install:
  - pip install -r requirements.txt --upgrade

script:
  - python3.5 -m pytest --disable-pytest-warnings test
