environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "$(PYTHON)\\python -m pip install -r requirements.txt --upgrade"

build: false

test_script:
  - "$(PYTHON)\\python -m pytest --disable-pytest-warnings test"
